name: meubcars
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # --- autres deps inchangées ---
  shared_preferences: ^2.2.2
  flutter_animate: ^4.1.1+1
  flutter_neumorphic: ^3.2.0
  flutter_staggered_grid_view: ^0.7.0
  curved_navigation_bar: ^1.0.3
  smooth_page_indicator: ^1.2.1

  # ✅ Compatibles avec intl 0.19.0
  syncfusion_flutter_gauges: ^30.2.7
  table_calendar: ^3.1.3   # <- downgrade (3.2.0 exige intl ^0.20.0)

  fl_chart: ^0.63.0
  timeline_tile: ^2.0.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  carousel_slider: ^5.0.0
  dio: ^5.8.0+1
  file_picker: ^8.0.0
  http_parser: ^4.1.2
  flutter_bloc: ^8.1.3
  jwt_decoder: ^2.0.1
  flutter_local_notifications: ^19.1.0
  signalr_core: ^1.1.1
  permission_handler: ^11.0.1
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.5
  flutter_svg: ^2.0.7
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  lottie: ^2.2.0
  flutter_native_splash: ^2.4.0
  google_nav_bar: ^5.0.6
  pdf: ^3.11.0
  printing: ^5.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/f24aad88-ac52-4ecf-9556-3923fadb60b5.png
    - assets/images/3c06a6eb-e895-4e7b-971d-2c11dba223c0.png
    - assets/images/fa255587-6402-42e0-a7df-b72b9f6f9e69.png
    - assets/images/avatar.png

flutter_icons:
  android: true
  image_path: "assets/images/images.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/meubcars_text.png
  android: true
  ios: true
  web: true
  android_12:
    color: "#FFFFFF"
    image: assets/images/meubcars_text.png
